WITH A AS (
    SELECT ID, ((RANK() OVER (ORDER BY SIZE_OF_COLONY DESC))/(COUNT(*) OVER ())) AS RATIO
    FROM ECOLI_DATA
)

SELECT ID, IF(RATIO <= 0.25, 'CRITICAL', IF(RATIO <= 0.5, 'HIGH', IF(RATIO <= 0.75, 'MEDIUM', 'LOW'))) AS COLONY_NAME
FROM A
ORDER BY ID ASC