-- 코드를 입력하세요
WITH CTE AS (SELECT WRITER_ID, COUNT(*) AS C
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING C >= 3)

SELECT B.USER_ID, B.NICKNAME, CONCAT(B.CITY, " ", B.STREET_ADDRESS1, " ", B.STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTRING(TLNO, 1, 3), "-", SUBSTRING(TLNO, 4, 4), "-", SUBSTRING(TLNO, 8, 4)) AS 전화번호
FROM CTE A
INNER JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
ORDER BY B.USER_ID DESC
