WITH A AS(
    SELECT USER_ID, JOINED
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),

MC AS(
SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT B.USER_ID) AS PURCHASED_USERS
FROM A
INNER JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
GROUP BY MONTH(SALES_DATE)
)

SELECT YEAR, MONTH, PURCHASED_USERS, ROUND((PURCHASED_USERS / (SELECT COUNT(*) FROM A)),1) AS PUCHASED_RATIO
FROM MC
ORDER BY 1 ASC, 2 ASC