WITH RECURSIVE ECOLI_HIERARCHY AS
(SELECT ID, 1 AS GENERATION
 FROM ECOLI_DATA
 WHERE PARENT_ID IS NULL
 
 UNION ALL
 
 SELECT A.ID, B.GENERATION + 1
 FROM ECOLI_DATA A
 INNER JOIN ECOLI_HIERARCHY B
 ON A.PARENT_ID = B.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM (SELECT ID FROM ECOLI_DATA WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
) A
INNER JOIN ECOLI_HIERARCHY B
ON A.ID = B.ID
GROUP BY GENERATION
ORDER BY GENERATION ASC