SELECT A.ID, A.NAME, A.HOST_ID
FROM PLACES A
RIGHT JOIN (SELECT HOST_ID, COUNT(*) AS NUM
            FROM PLACES
           GROUP BY HOST_ID) B
ON A.HOST_ID = B.HOST_ID
WHERE B.NUM > 1
ORDER BY ID ASC