WITH CTE AS (
SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
)

SELECT B.USER_ID, B.NICKNAME, A.TOTAL_SALES
FROM CTE A
INNER JOIN USED_GOODS_USER B
WHERE A.WRITER_ID = B.USER_ID AND A.TOTAL_SALES >= 700000
ORDER BY A.TOTAL_SALES ASC